<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>edit stamps</title>
</head>
<body>
<form action="/home/editsub" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id" value="<?= $post->id ?>">

    <input type="text" name="title" value="<?=$post->title?>">
    <br>
    <input type="text" name="content" value="<?=$post->content?>">
    <br>
   <button type="submit">Update</button>
</form>
</body>
</html>