<!DOCTYPE html>
<html>
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
<head>
	<title>Home</title>
	<style type="text/css">
		body {
			margin:auto;
			padding: 10px;
			background-image: url("images/bgMain.jpg");
			font-family: 'Permanent Marker', cursive;
			font-size: 14px;
		}
		a:hover a:active a:visited{
			color:black;
		}
		.flip-card {
			display:inline-block;
			background-color: transparent;
			width: 300px;
			height: 300px;
			perspective: 1000px;
			/* Remove this if you don't want the 3D effect */
			border-radius:10%;
			
			
		}

		/* This container is needed to position the front and back side */
		.flip-card-inner {
			position: relative;
			width: 100%;
			height: 100%;
			text-align: center;
			transition: transform 0.8s;
			transform-style: preserve-3d;
		}

		/* Do an horizontal flip when you move the mouse over the flip box container */
		.flip-card:hover .flip-card-inner {
			transform: rotateY(180deg);
		}

		/* Position the front and back side */
		.flip-card-front,
		.flip-card-back {
			position: absolute;
			width: 100%;
			height: 100%;
			backface-visibility: hidden;
		}

		/* Style the front side (fallback if image is missing) */
		.flip-card-front { 
			
			background-color: #bbb;
			color: black;
		}
		

		/* Style the back side */
		.flip-card-back {
			background-color: dodgerblue;
			color: white;
			transform: rotateY(180deg);
		}
	</style>
</head>

<body>
	<?php foreach($posts as $p) { ?>
	<div class="flip-card">
		<div class="flip-card-inner">
			<div class="flip-card-front">
				<img class="cardImage" src="/images/<?=$p->image ?>" alt="Avatar" style="width:300px;height:300px;">
			</div>
			<div class="flip-card-back">
				<h1><?= $p->title ?></h1>
				<p><?= $p->content?></p>
				<p><?= $p->inserted?></p>
				<p><a href="/home/edit?id=<?= $p->id ?>">edit the stamp</a></p>
				<p><a href="/home/delete?id=<?= $p->id ?>">delete the stamp</a></p>
			</div>
		</div>
	</div>
	<?php } ?>

	<h1><a href="/upload">upload a new stamp</a></h1>
	
</body>

</html>