<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div id="contactleft">
	<h1>Contact me</h1>
	<p>Please contact me</p>
	</div>
	<div id="contactright">
		<form action="/contact/submit" method="post">
			<input type="input" name="name" placeholder="name"><br>
			<input type="input" name="email" placeholder="email"><br>
			<input type="input" name="message" placeholder="message"><br>
			<button type="submit" class="button">Submit</button>
		</form>
	</div>
	<p><a href="/home">Home</a></p>
</body>
</html>